services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  testpostgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2
    ports:
      - "5672:5672"
    volumes:
     - ./rabbitmq-volume:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  rabbitmq-management:
    container_name: rabbitmq-management
    image: rabbitmq:3-management
    ports:
      - "8800:15672"
    depends_on:
      - rabbitmq

