services:
  nginx-lb:
    container_name: nginx-lb
    image: nginx:1.29
    ports:
      - "8080:80"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/load-balancer.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
    - "host.docker.internal:host-gateway"
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql

  testpostgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432"

  rabbitmq:
    hostname: "rabbit"
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "8800:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
